num_samples: 16900
input_dim: 2
dataset: 3

# must be total 1.0
train_split: 0.95
test_split: 0.05

num_epochs: 0
rho: 0.85
lip: 1.0 # Lipschitz constant
tol_abs: 1e-5
tol_rel: 1e-3
backend: 'gloo'

graph_viz: False