num_samples: 16900
input_dim: 2
dataset: 2

# must be total 1.0
train_split: 0.95
test_split: 0.05

num_epochs: 0
rho: 0.75
lip: 1.0 # Lipschitz constant
tol_abs: 1e-5
tol_rel: 1e-3
backend: 'gloo'

aug_dataset_size: 100

graph_viz: False