# training configuration for gapxGP

num_samples: 1000
input_dim: 1
num_epochs: 100
rho: 0.8
lip: 1.0 # Lipschitz constant
tol_abs: 1e-5
tol_rel: 1e-3
backend: 'gloo'

# data augmentation
aug_dataset_size: 100