num_samples: 30000
input_dim: 2
dataset: 6

# must be total 1.0
train_split: 0.95
test_split: 0.05

num_epochs: 100
rho: 1.0
lip: 2.0 # Lipschitz constant
tol_abs: 1e-3
tol_rel: 5e-2
backend: 'gloo'

# data augmentation
aug_dataset_size: 50